create table tb_wishlist (id bigint not null, product_id bigint array, primary key (id));
create table tb_wishlist_product (id bigint generated by default as identity, list_id bigint not null, product_id bigint not null, primary key (id));
