create table tb_cart (id bigint not null, product_id bigint array, primary key (id));
create table tb_cart_product (cart_id bigint not null, id bigint generated by default as identity, product_id bigint not null, primary key (id));
